:sparkles: allow specifying the branch to install
pearl-core/installer pull request #2
Opened 2018-05-18 23:04 UTC by go2null

2018-05-19 10:20 UTC, fsquillace requested changes
Thanks a lot for this PR! It looks great.

I just put a minor comment.

2018-05-19 10:20 UTC, fsquillace commented on install.sh
> +[ -n "$1" ] && branch="--branch $1" || unset branch
Can we use the double brackets ``[[`` ? I am trying to move all codebase with this.

2018-05-22 13:16 UTC, go2null commented
Changed from POSIX to Bash test brackets (`[..]` to `[[..]]`).

2018-05-22 13:54 UTC, go2null commented
Fixed missing space at beginning of second sentence of Error message.

2018-05-23 09:07 UTC, fsquillace approved these changes

2018-05-23 09:07 UTC, merged

2018-05-23 09:15 UTC, fsquillace commented
Thanks again. I was thinking to add a contributor file to pearl package when i have time. I will add your name into it. Feel free to create PR for it too if you have time.